### ISSUE TITLE
你好，请问如何查看是否安装成功？谢谢

### ISSUE THREAD

**Issue by qnyblog** [bemarkt/UDPtools#4]
你好，请问如何查看是否安装成功？谢谢

UDPspeeder&UDP2raw安装完成

                UDPspeeder      使用端口：本地：7776    远程：1025
                UDP2raw         使用端口：本地：7775    远程：7776
                当前 IP：94.xxx.xxx.xxx  来自于：德国 黑森州 法兰克福  xxxxxx.com

                输入 screen -r udpspeeder 查看udpspeeder
                输入 screen -r udp2raw 查看udp2raw

这样算成功安装并使用吗？谢谢

**Comment by bemarkt** [comment]
是的，可以运行udp2raw以及udpspeeder的client端进行测试

**Comment by qnyblog** [comment]
谢谢
